import pytest

from imp_git import validate


class TestCommit:

   @pytest.mark.parametrize ("msg", [
      "feat: add login page",
      "fix: resolve null pointer",
      "refactor(auth): simplify token flow",
      "build: IMP-123 update deploy script",
      "chore!: drop node 14 support",
   ])
   def test_valid (self, msg):
      assert validate.commit (msg)

   @pytest.mark.parametrize ("msg", [
      "Add login page",
      "FEAT: uppercase type",
      "feat:",
      "feat:missing space",
      "feat: Uppercase description",
      "fix: add final period.",
      "feat(Bad Scope): add value",
      "feat: add value\n\nCo-Authored-By: Bot <bot@example.com>",
      "feat: " + "x" * 80,
   ])
   def test_invalid (self, msg):
      assert not validate.commit (msg)


class TestPublishable:

   @pytest.mark.parametrize ("text", [
      "Co-Authored-By: Bot <bot@example.com>",
      "Generated-By: Claude Code",
      "Assisted-By: GitHub Copilot",
      "Generated with Claude Code",
      "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
      "This pull request was generated by OpenAI Codex.",
      "This change was co-authored by Claude.",
      "Written with help from Gemini",
      "Claude Code helped write this code.",
      "AI-assisted by Claude",
      "actor:codex:payment-agent",
   ])
   def test_rejects_provenance (self, text):
      assert not validate.publishable (text)

   @pytest.mark.parametrize ("text", [
      "feat: add OpenAI provider",
      "docs: explain Claude model selection",
      "Responses are generated by OpenAI at request time.",
      "Generated-By: protoc 27.1",
      "Document the AI-generated content policy",
   ])
   def test_allows_subject_matter (self, text):
      assert validate.publishable (text)

   def test_detects_new_provenance (self):
      assert validate.adds_provenance ("# Guide\n", "# Guide\n\nGenerated with Claude Code\n")

   def test_allows_existing_provenance (self):
      text = "Example: actor:codex:payment-agent\n"

      assert not validate.adds_provenance (text, text + "More detail.\n")


class TestBranch:

   @pytest.mark.parametrize ("name", [
      "main",
      "feat/my-feature",
      "fix/bug-123",
      "release/1.0.0",
   ])
   def test_valid (self, name):
      assert validate.branch (name)

   @pytest.mark.parametrize ("name", [
      "feat/my feature",
      "feat;rm -rf",
      "-delete",
   ])
   def test_invalid (self, name):
      assert not validate.branch (name)
